apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: tasdis-microsservices
build:
  local:
    # useBuildkit: true
    # concurrency: 0
    push: true
  artifacts:
    - image: ghcr.io/llunno/tasdis-bff
      context: bff
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
      # docker:
      #   dockerfile: Dockerfile
    - image: ghcr.io/llunno/tasdis-curso
      context: microsservice_curso
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
      # docker:
      #   dockerfile: Dockerfile
    - image: ghcr.io/llunno/tasdis-endereco
      context: microsservice_endereco
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
      # docker:
      #   dockerfile: Dockerfile
    - image: ghcr.io/llunno/tasdis-gateway
      context: gateway
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
    - image: ghcr.io/llunno/tasdis-instituicao
      context: microsservice_instituicao
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
      # docker:
      #   dockerfile: Dockerfile
    - image: ghcr.io/llunno/tasdis-tarefa
      context: microsservice_tarefa
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
      # docker:
      #   dockerfile: Dockerfile
    - image: ghcr.io/llunno/tasdis-usuario
      context: microsservice_usuario
      jib:
        fromImage: gcr.io/distroless/java:debug
        args:
          - "-DskipTests"
      sync:
        auto: true
      # docker:
      #   dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes/bff-deployment.yaml
    - kubernetes/bff-service.yaml
    - kubernetes/curso-deployment.yaml
    - kubernetes/curso-service.yaml
    - kubernetes/endereco-deployment.yaml
    - kubernetes/endereco-service.yaml
    - kubernetes/gateway-deployment.yaml
    - kubernetes/gateway-service.yaml
    - kubernetes/instituicao-deployment.yaml
    - kubernetes/instituicao-service.yaml
    - kubernetes/tarefa-deployment.yaml
    - kubernetes/tarefa-service.yaml
    - kubernetes/usuario-deployment.yaml
    - kubernetes/usuario-service.yaml
