apiVersion: apps/v1
kind: Deployment
metadata:
  name:  endereco
  namespace: default
  labels:
    app:  endereco
spec:
  selector:
    matchLabels:
      app: endereco
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  endereco
    spec:
      containers:
      - name:  endereco
        image:  ghcr.io/llunno/tasdis-endereco:latest
        ports:
        - containerPort:  8083
          name:  endereco
      restartPolicy: Always